import invariant from 'tiny-invariant'
import type { SignMessageReturnType } from 'viem'
import type { BaseConfig } from './createConfig.js'
import type * as rustUtils from './utils.d.ts'

export type CreateBYOKConfigParameters = {
  /** URL of the relayer service */
  relayerUrl: string
  /** URL of the websocket service */
  websocketUrl: string
  /**
   * Function to sign messages using the user's own wallet.
   *
   * TODO: Move this to docs
   * Important requirements for the signing function:
   * 1. The function receives a pre-hashed message (using keccak256) - do not hash the message again
   * 2. Do not prefix the message - sign it as is
   * 3. The signature must use `0x00` or `0x01` for the `v` value (y-parity)
   *    Do not use Ethereum-specific values `0x1b` or `0x1c` which add an offset of 27
   * 4. When using libraries like viem, avoid using `serializeSignature` as it normalizes `v` to `0x1b`/`0x1c`
   *    Instead, manually construct the 65-byte signature by concatenating `r`, `s`, and recovery byte (`0x00`/`0x01`)
   */
  signMessage: (message: string) => Promise<SignMessageReturnType>
  // Wallet secrets generated by offline script
  symmetricKey: `0x${string}`
  walletId: string
  publicKey: `0x${string}`
  utils?: typeof rustUtils
}

/**
 * Creates a configuration for users who want to bring their own keychain (BYOK).
 *
 * This configuration differs from the standard createConfig by allowing users to maintain
 * custody of their wallet secrets while still enabling interaction with the relayer for
 * wallet operations. Instead of managing keys internally, it accepts user-provided
 * cryptographic materials and signing functions.
 */
export function createBYOKConfig(
  parameters: CreateBYOKConfigParameters,
): BYOKConfig {
  const {
    relayerUrl,
    signMessage,
    symmetricKey,
    walletId,
    publicKey,
    websocketUrl,
  } = parameters
  invariant(
    parameters.utils,
    'Utils must be provided by the package if not supplied by the user.',
  )
  return {
    // BYOK
    signMessage,
    symmetricKey,
    walletId,
    publicKey,
    // BaseConfig
    getRelayerBaseUrl: (route = '') => {
      const formattedRoute = route.startsWith('/') ? route : `/${route}`
      return `${relayerUrl}/v0${formattedRoute}`
    },
    getWebsocketBaseUrl: () => {
      return websocketUrl.replace(/\/$/, '')
    },
    utils: parameters.utils,
    relayerUrl,
  }
}

export type BYOKConfig = BaseConfig & {
  getRelayerBaseUrl: (route?: string) => string
  relayerUrl: string
  signMessage: (message: string) => Promise<SignMessageReturnType>
  symmetricKey: `0x${string}`
  walletId: string
  publicKey: `0x${string}`
}
